# Generated by Django 3.1.2 on 2021-06-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Marca',
            new_name='marca',
        ),
    ]
