# Generated by Django 3.1.2 on 2021-06-13 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='codigoBarra',
            new_name='codigo_de_Barras',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='fechaIngreso',
            new_name='fecha_de_Ingreso',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precioCosto',
            new_name='precio_Costo',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precioVenta',
            new_name='precio_Venta',
        ),
    ]
