# Generated by Django 3.1.2 on 2021-06-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210614_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_Paterno', models.CharField(max_length=50)),
                ('apellido_Materno', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_de_Nacimiento', models.DateField()),
                ('nivel_Educacional', models.IntegerField(choices=[[0, 'Educación Básica'], [1, 'Educación Media'], [2, 'Educación Superior'], [3, 'Bachiller'], [4, 'Licenciado'], [5, 'Magister'], [6, 'Doctorado'], [7, 'Otro']])),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
    ]
