# Generated by Django 3.1.2 on 2021-06-14 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.pais'),
        ),
    ]
