# Generated by Django 3.1.2 on 2021-06-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210614_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='digito_verificador',
            field=models.IntegerField(choices=[[0, '0'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7'], [8, '8'], [9, '9'], [10, 'K']]),
        ),
    ]
