# Generated by Django 3.1.2 on 2021-06-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210614_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido_Materno',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido_Paterno',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.TextField(max_length=50),
        ),
    ]
