# Generated by Django 3.1.2 on 2021-06-16 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210616_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('digito_verificador', models.IntegerField(choices=[[0, '0'], [1, '1'], [3, '2'], [4, '3'], [5, '4'], [6, '5'], [7, '6'], [8, '7'], [9, '8'], [10, '9'], [11, 'K']])),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_Paterno', models.CharField(max_length=50)),
                ('apellido_Materno', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_de_Nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_costo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiene_azucar',
            field=models.IntegerField(choices=[[0, 'Si'], [1, 'No']], null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiene_lactosa',
            field=models.IntegerField(choices=[[0, 'Si'], [1, 'No']], null=True),
        ),
        migrations.RenameModel(
            old_name='Pais',
            new_name='Comuna',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.comuna'),
        ),
    ]
