# Generated by Django 3.2.3 on 2021-07-03 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210616_0628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pastel',
            new_name='Producto',
        ),
    ]
