# Generated by Django 3.2.3 on 2021-07-05 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_cliente_digito_verificador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_costo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tiene_azucar',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tiene_lactosa',
        ),
    ]
